export const data = [
  {
    id: 1,
    title: "GINGER LIME",
    heading1: "FRESH ",
    heading2: " GINGER",
    heading3: " LIME",
    subheading1: "Ignite your senses,",
    subheading2: "Embrace the warmth.",
    text: "Gingergroove is meticulously crafted with a blend of natural ingredients, each selected for its quality, flavor, and health benefits, ensuring that every sip offers not just a delightful taste but also a nourishing experience.",
    ingredients: {
      ing1: "Premium Ginger Extract",
      ing2: "Natural Sweeteners",
      ing3: "Purified Water, Citrus Notes",
      ing4: "Herbs and Spices",
      ing5: "Essential Minerals and Vitamins",
    },
    Alcohol: "0%",
    VOLUME: "250ml",
    storage: "30'c",
    calories: "160",
    colors: {
      background: "#FF9D5C",
      h1: "#000000",
      text: "#ffffff",
      button: "#EB5C35",
    },
  },
  {
    id: 2,
    title: "BERRY BLAST",
    heading1: "WILD ",
    heading2: " BERRY",
    heading3: " BLAST",
    subheading1: "Awaken your buds,",
    subheading2: "Indulge in the burst.",
    text: "BerryBlast is a delightful fusion of berries, each handpicked to ensure the perfect balance of sweetness and tartness, delivering a refreshing and invigorating drink that's as nutritious as it is delicious.",
    ingredients: {
      ing1: "Mixed Berry Extract",
      ing2: "Natural Sweeteners",
      ing3: "Purified Water, Berry Essence",
      ing4: "Herbs and Spices",
      ing5: "Essential Minerals and Vitamins",
    },
    Alcohol: "10%",
    VOLUME: "350ml",
    storage: "30'c",
    calories: "200",
    colors: {
      background: "#D65DB1",
      h1: "#000",
      text: "#fff",
      button: "#C70067",
    },
  },
  {
    id: 3,
    title: "CITRUS ZEST",
    heading1: "ZESTY ",
    heading2: " CITRUS",
    heading3: " ZEST",
    subheading1: "Revitalize your palate,",
    subheading2: "Savor the citrus zing.",
    text: "CitrusZest combines the juiciest citrus fruits with a hint of sweetness, creating a drink that's both refreshing and energizing, perfect for a burst of flavor and a boost of vitality.",
    ingredients: {
      ing1: "Citrus Fruit Extract",
      ing2: "Natural Sweeteners",
      ing3: "Purified Water, Citrus Essence",
      ing4: "Herbs and Spices",
      ing5: "Essential Minerals and Vitamins",
    },
    Alcohol: "5%",
    VOLUME: "200ml",
    storage: "30'c",
    calories: "250",
    colors: {
      background: "#FFC300",
      h1: "#000",
      text: "#fff",
      button: "#FF5733",
    },
  },
];
